ChatApp/ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('accounts/', include('allauth.urls')),
]

chat/chat/urls.py
from django.contrib.auth.views import logout
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('chat/verify/', views.verify, name='verify'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    path('logout/', logout, {'next_page': 'index'}, name='logout'),
    path('register/', views.register_view, name='register'),
    path('send_email/', views.send_email, name='send_email'),
]

chat/urls.py
from django.contrib.auth import logout
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('chat/verify/', views.verify, name='verify'),
    path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    path('api/messages/', views.message_list, name='message-list'),
    path('logout/', logout, {'next_page': 'index'}, name='logout'),
    path('register/', views.register_view, name='register'),
    path('send_email/', views.send_email, name='send_email'),
]

chat/chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_code = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.email_code

chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    private_key = models.TextField(blank=True)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_code = models.CharField(max_length=100, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.email_code

chat/chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import EmailInput


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
            'username': EmailInput(attrs={'class': 'form-control'}),
        }

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import EmailInput


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        widgets = {
            'username': EmailInput(attrs={'class': 'form-control'}),
        }

chat/chat/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from chat.models import Message
from chat.forms import SignUpForm
from chat.serializers import MessageSerializer
from .models import Profile
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from ChatApp import settings

def index(request):
    """
        Django Project Starts From here!
        if it's login it can directly go to the chat page otherwise login page on get request...
        if it's not login it can directly go to the Login/Register page...
    """
    if request.user.is_authenticated:

        return redirect('chats')
    if request.method == 'GET':
        return render(request, 'chat/index.html', {})
    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)

        else:
            return render(request, 'chat/index.html',
                          {'errors': "Wrong Login Id/Password OR User DoesNot Exist!"}
                          )
    return redirect('chats')



@csrf_exempt
def message_list(request, sender=None, receiver=None):
    """
            List all required messages, or start a new chat.
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)


def register_view(request):
    """
        Render registration Page
    """
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.email = username
            user.save()

            import random
            code = str(random.random())
            profile = Profile(user=user, email_code=code)
            profile.save()

            if code:
                print()
                subject = "Verification Email"
                body = {
                    'subject': "Verification | DBS Chat System",
                    'message': 'verification code is: ' + str(code),
                }
                message = '\n'.join(body.values())
                sender = settings.EMAIL_HOST_USER
                recipient = [username, ]
                try:
                    send_mail(subject, message, sender, recipient)
                    print("+++++++ Email Sent +++++++")
                except Exception as e:
                    return HttpResponse(str(e))

            else:
                return HttpResponse('Make sure all fields are entered and valid.')

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('chats')
        else:
            print(form.errors)
            template = 'chat/register.html'
            context = {'form': form,
                       'errors': form.errors
                       }
            return render(request, template, context)

    else:
        form = SignUpForm()
    template = 'chat/register.html'
    context = {'form': form}
    return render(request, template, context)


def chat_view(request):
    """
        Main Page of Chat App where all the users come at left side.
        and chat at the right side
    """
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        profile = Profile.objects.get(user=User.objects.get(email=request.user.email))
        return render(request, 'chat/chat.html',
                      {'users': User.objects.exclude(username=request.user.username),
                       'verified': profile.is_verified})


def message_view(request, sender, receiver):
    """
        If user is not authenticated then it will go to the index route
        otherwise will go to the chat dashboard page
    """
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        profile = Profile.objects.get(user=User.objects.get(email=request.user.email))
        return render(request, "chat/messages.html",
                      {'users': User.objects.exclude(username=request.user.username),
                       'receiver': User.objects.get(id=receiver),
                       'messages': Message.objects.filter(sender_id=sender, receiver_id=receiver) |
                                   Message.objects.filter(sender_id=receiver, receiver_id=sender),
                       'verified': profile.is_verified})


def send_email(request):
    import random
    profile = Profile.objects.get(user=User.objects.get(email=request.user.email))
    code = str(random.random())
    if code:
        print()
        subject = "Verification Email"
        body = {
            'subject': "Verification | DBS Chat System",
            'message': 'verification code is: ' + str(code),
        }
        message = '\n'.join(body.values())
        sender = settings.EMAIL_HOST_USER
        recipient = [profile.user.username, ]
        try:
            send_mail(subject, message, sender, recipient)
            print("+++++++ Email Sent +++++++")
            return HttpResponse('Email Sent')
        except Exception as e:
            return HttpResponse(str(e))

    else:
        return HttpResponse('Make sure all fields are entered and valid.')


def verify(request):
    code = request.POST.get('code', None)
    if code:
        try:
            profile = Profile.objects.get(user=request.user)
            if profile.email_code == code:
                profile.is_verified = True
                profile.save()
                return redirect('chats')
            else:
                return HttpResponse('Wrong Verification Code!')
        except Exception as e:
            return HttpResponse(str(e))
    else:
        return HttpResponse('No Verification Code Found')
    return redirect('chats')

templates/chat/chat.html
{% extends 'chat/index.html' %}
{% block body %}
<nav class="bg-primary">
    <div class="nav-wrapper container">
      <p  class="brand-logo">DBS Students Chatting App</p>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li class="text-capitalize"><a href="">{{ request.user.username }}</a></li>
          <li class="text-capitalize"><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-2">
        <div class="card">

            <div class="collection">
                {% if verified %}
                    {% for user in users %}
                        <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                    <div class="col">

                            <span class="title text-capitalize" style="font-weight: bolder">{{ user.username }}</span>

                    </div>
                </a>
                    {% endfor %}
                {% else %}
                        <p class="p-1 text-danger border-bottom">Please Verify your Email First.</p>
                        <form action="{% url 'verify' %}" method="POST" class="text-center py-2">
                                {% csrf_token %}
                                <input name="code" id="code" placeholder="Enter Email Code">
                                <input type="submit" class="btn btn-primary" value="Verify"><hr>
                                <a href="{% url 'send_email'%}">Resend Code</a>
                        </form>
                {% endif %}
            </div>
        </div>
        </div>
        <div class="col-lg-9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row justify-content-center">
                    <div class="col-11">
                        <div class="input-field">
                            <input id="id_message" name="message" class="form-control" type="text" placeholder="  Type your message..">
                        </div>
                    </div>
                    <div class="col-1" style="line-height: 80px">
                        <button class="btn btn-floating blue lighten-2 waves-effect waves-light">
                            <i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load staticfiles %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock %}

templates/chat/index.html
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
    {% block body %}
        <div class="bg-light border  py-3 container-fluid">
            <div class="container text-dark text-center ">
            <h2>DBS Students Chatting App</h2>
            <p>Django Chatting App</p>
            </div>
        </div>
        <div class="container p-3 text-primary">
            <div class="row justify-content-center my-3">
            <div class="col-6 ">
                <div class="text-center py-3">
                <div>
                    {% block form %}
                    <h3>
                            Login to Proceed
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12 my-3">
                                <input name="username" id="id_username" type="email" required>
                                <label for="id_username">Email</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12 my-3">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="text-center text-danger m-2">
                                {% if errors %}
                                        {{ errors }}
                                {% endif %}
                            </div>
                            <div class="col">
                                <a class=" btn  text-dark btn-primary" href="{% url 'register' %}">Register</a>
                            </div>

                            <div class="col">
                                <button class=" btn text-dark btn-primary">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>

  </html>

templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group" method="POST">
        {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    {{ form.username }}
                    <label for="id_username" data-error="Username already taken">Email</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password1 }}
                    <label for="id_password">Password</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password2 }}
                    <label for="id_password2">Repeat Password</label>
                </div>
            </div>
            <div class="row">
                <div>
                    {% if errors %}
                          {{ errors }}
                    {% endif %}
                </div>
                <div class="col s12">
                            <div class="col">
                                <a class=" btn  text-dark btn-primary" href="{% url 'index' %}">Login</a>
                            </div>
                    <div class="right">
                    <button class="btn blue waves-effect waves-light pull-s12">Register</button>
                </div>

                </div>
            </div>
    </form>
{% endblock %}